 export const config1 = [
    {
        "id": 1,
        "width": 193,
        "height": 26,
        "type": "text",
        "content": "运动浙江 户外天堂",
        "elementField": "",
        "fontSize": 20,
        "textAlign": "center",
        "color": "#000000",
        "top": 30,
        "left": 110,
        "fontWeight": 300
    },
    {
        "id": 2,
        "width": 320,
        "height": 170,
        "type": "image",
        "content": "封面图",
        "elementField": "封面图",
        "src": "https://s1.ax1x.com/2022/06/24/jircW9.jpg",
        "radius": 0,
        "top": 85,
        "left": 30,
        "scale": false
    },
    {
        "id": 3,
        "width": 68,
        "height": 68,
        "type": "qrCode",
        "content": "二维码",
        "elementField": "",
        "qrtext": "https://s1.ax1x.com/2022/08/24/vgmFTf.png",
        "top": 396,
        "left": 289,
        "scale": true
    },
    {
        "id": 4,
        "width": 70,
        "height": 70,
        "type": "image",
        "content": "图片4",
        "elementField": "",
        "src": "https://vkceyugu.cdn.bspapp.com/VKCEYUGU-699d1eb1-ee53-4c66-bddd-06cda80d1231/01acf825-4f59-4592-8034-295d16e69c7e.png",
        "top": 10,
        "left": 30,
        "scale": true
    },
    {
        "id": 5,
        "width": 265,
        "height": 35,
        "type": "text",
        "content": "标题",
        "elementField": "标题",
        "fontSize": 14,
        "color": "#000000",
        "top": 269,
        "left": 50,
        "fontWeight": 600,
        "textAlign": "left"
    },
    {
        "id": 6,
        "width": 60,
        "height": 20,
        "type": "text",
        "content": "播放量",
        "elementField": "播放量",
        "fontSize": 14,
        "color": "#000000",
        "top": 320,
        "left": 50,
        "fontWeight": 300,
        "textAlign": "center"
    },
    {
        "id": 7,
        "width": 70,
        "height": 20,
        "type": "text",
        "content": "点赞数量",
        "elementField": "点赞数量",
        "fontSize": 14,
        "color": "#000000",
        "top": 320,
        "left": 125,
        "fontWeight": 300,
        "textAlign": "center"
    },
    {
        "id": 8,
        "width": 100,
        "height": 20,
        "type": "text",
        "content": "收藏数量",
        "elementField": "收藏数量",
        "fontSize": 14,
        "color": "#000000",
        "top": 320,
        "left": 208,
        "fontWeight": 300,
        "textAlign": "center"
    },
    {
        "id": 9,
        "width": 60,
        "height": 60,
        "type": "image",
        "content": "作者头像",
        "elementField": "作者头像",
        "src": "",
        "top": 400,
        "left": 30,
        "scale": true
    },
    {
        "id": 10,
        "width": 100,
        "height": 20,
        "type": "text",
        "content": "作者昵称",
        "elementField": "作者昵称",
        "fontSize": 14,
        "color": "#000000",
        "top": 421,
        "left": 80,
        "fontWeight": 300,
        "textAlign": "center"
    }
]